const products = [
    { name: "Apple iPhone 14", description: "Latest model of iPhone with great features", price: 999, category: "smartphones", brand: "Apple" },
    { name: "Samsung Galaxy S22", description: "High-end Android smartphone with amazing camera", price: 899, category: "smartphones", brand: "Samsung" },
    { name: "Dell XPS 13", description: "Ultra-portable laptop with powerful performance", price: 1299, category: "laptops", brand: "Dell" },
    { name: "MacBook Pro M1", description: "Apple's powerful laptop with M1 chip", price: 2399, category: "laptops", brand: "Apple" },
    { name: "Sony WH-1000XM4", description: "Noise-canceling wireless headphones", price: 350, category: "headphones", brand: "Sony" },
    { name: "Bose QuietComfort 35 II", description: "Wireless noise-canceling headphones", price: 300, category: "headphones", brand: "Bose" },
    { name: "Nike Air Max 270", description: "Comfortable and stylish running shoes", price: 150, category: "shoes", brand: "Nike" },
    { name: "Adidas Ultraboost 22", description: "Running shoes with great cushioning", price: 180, category: "shoes", brand: "Adidas" },
    { name: "Sony PlayStation 5", description: "Next-gen gaming console with powerful features", price: 499, category: "gaming", brand: "Sony" },
    { name: "Xbox Series X", description: "Powerful gaming console from Microsoft", price: 499, category: "gaming", brand: "Microsoft" },
    { name: "Canon EOS R5", description: "Mirrorless camera with high resolution", price: 3899, category: "cameras", brand: "Canon" },
    { name: "Nikon Z6 II", description: "Full-frame mirrorless camera with amazing autofocus", price: 1999, category: "cameras", brand: "Nikon" },
    { name: "GoPro HERO10 Black", description: "Action camera with high-definition recording", price: 399, category: "cameras", brand: "GoPro" },
    { name: "Samsung 49\" Odyssey Monitor", description: "Ultra-wide monitor with 144Hz refresh rate", price: 900, category: "electronics", brand: "Samsung" },
    { name: "LG OLED55CXPUA", description: "55-inch OLED TV with stunning picture quality", price: 1500, category: "electronics", brand: "LG" },
    { name: "Apple Watch Series 7", description: "Smartwatch with fitness tracking and health features", price: 399, category: "smartwatches", brand: "Apple" },
    { name: "Garmin Fenix 6 Pro", description: "Multisport GPS watch with advanced features", price: 649, category: "smartwatches", brand: "Garmin" },
    { name: "Fujifilm X-T4", description: "Mirrorless camera with 4K video and amazing photo quality", price: 1699, category: "cameras", brand: "Fujifilm" },
    { name: "MSI GE76 Raider", description: "Gaming laptop with Intel i9 and RTX 3080", price: 1999, category: "laptops", brand: "MSI" },
    { name: "Asus ROG Strix", description: "Gaming laptop with powerful specs and RGB lighting", price: 1599, category: "laptops", brand: "Asus" },
    { name: "Apple iPad Air", description: "Lightweight tablet with A14 Bionic chip", price: 599, category: "tablets", brand: "Apple" },
    { name: "Samsung Galaxy Tab S7", description: "High-performance Android tablet with S Pen", price: 649, category: "tablets", brand: "Samsung" },
    { name: "Microsoft Surface Pro 7", description: "2-in-1 tablet with laptop performance", price: 799, category: "tablets", brand: "Microsoft" },
    { name: "Lenovo ThinkPad X1 Carbon", description: "Ultra-lightweight business laptop with great performance", price: 1600, category: "laptops", brand: "Lenovo" },
    { name: "Google Pixel 6", description: "Smartphone with great camera and clean Android experience", price: 599, category: "smartphones", brand: "Google" },
    { name: "Oculus Quest 2", description: "All-in-one VR headset with immersive experience", price: 299, category: "gaming", brand: "Oculus" },
    { name: "JBL Flip 5", description: "Portable Bluetooth speaker with great sound", price: 120, category: "electronics", brand: "JBL" },
    { name: "Apple AirPods Pro", description: "Noise-canceling wireless earbuds with great sound", price: 249, category: "electronics", brand: "Apple" },
    { name: "Sony A7 III", description: "Full-frame mirrorless camera for professional photographers", price: 1999, category: "cameras", brand: "Sony" },
    { name: "HP Spectre x360", description: "Convertible laptop with sleek design and powerful specs", price: 1499, category: "laptops", brand: "HP" },
    { name: "TCL 6-Series 65\"", description: "65-inch 4K UHD smart TV", price: 799, category: "electronics", brand: "TCL" },
    { name: "Razer Blade 15", description: "High-performance gaming laptop", price: 1799, category: "laptops", brand: "Razer" },
    { name: "Bose SoundLink Revolve", description: "Portable Bluetooth speaker with 360° sound", price: 199, category: "electronics", brand: "Bose" },
    { name: "Apple MacBook Air M2", description: "Lightweight and powerful laptop with M2 chip", price: 1199, category: "laptops", brand: "Apple" },
    { name: "Samsung Galaxy Watch 4", description: "Smartwatch with health features and great design", price: 249, category: "smartwatches", brand: "Samsung" },
    { name: "Nvidia GeForce RTX 3080", description: "Powerful graphics card for gaming and professional use", price: 699, category: "electronics", brand: "Nvidia" },
    { name: "Corsair Vengeance LPX", description: "High-performance RAM for gaming and productivity", price: 80, category: "electronics", brand: "Corsair" },
    { name: "Alienware Aurora R12", description: "Gaming desktop with powerful specs and RGB lighting", price: 2200, category: "gaming", brand: "Alienware" },
    { name: "Microsoft Xbox Series S", description: "Affordable next-gen gaming console", price: 299, category: "gaming", brand: "Microsoft" },
    { name: "Vizio 50\" 4K Smart TV", description: "50-inch 4K UHD TV with smart features", price: 500, category: "electronics", brand: "Vizio" },
    { name: "Logitech G Pro X", description: "Gaming headset with Blue VO!CE microphone technology", price: 130, category: "electronics", brand: "Logitech" },
    { name: "Harman Kardon Onyx Studio 6", description: "Portable Bluetooth speaker with deep bass", price: 349, category: "electronics", brand: "Harman Kardon" },
    { name: "Turtle Beach Stealth 700", description: "Wireless gaming headset with great sound quality", price: 150, category: "electronics", brand: "Turtle Beach" },
    { name: "Logitech G502 Hero", description: "Gaming mouse with customizable buttons", price: 50, category: "electronics", brand: "Logitech" },
    { name: "HyperX Cloud II", description: "Gaming headset with virtual surround sound", price: 99, category: "electronics", brand: "HyperX" },
    { name: "Bose Noise Cancelling Headphones 700", description: "High-quality noise-canceling headphones", price: 379, category: "headphones", brand: "Bose" },
    { name: "SteelSeries Arctis 7", description: "Wireless gaming headset with long battery life", price: 150, category: "electronics", brand: "SteelSeries" },
    { name: "Apple iPhone 13", description: "Previous generation iPhone with excellent camera", price: 899, category: "smartphones", brand: "Apple" },
    { name: "Samsung Galaxy Z Fold 3", description: "Foldable smartphone with a unique design", price: 1799, category: "smartphones", brand: "Samsung" },
    { name: "Samsung Galaxy A52", description: "Mid-range smartphone with solid performance", price: 350, category: "smartphones", brand: "Samsung" },
    { name: "Acer Predator Helios 300", description: "Gaming laptop with RTX 3060 and i7", price: 1399, category: "laptops", brand: "Acer" },
    { name: "Alienware X17", description: "High-performance gaming laptop with powerful graphics", price: 2199, category: "laptops", brand: "Alienware" },
    { name: "Sony Xperia 5 II", description: "Android smartphone with excellent display and camera", price: 999, category: "smartphones", brand: "Sony" },
    { name: "OnePlus 9 Pro", description: "Flagship smartphone with powerful performance", price: 1069, category: "smartphones", brand: "OnePlus" },
    { name: "Google Pixel 5", description: "Affordable flagship smartphone with clean software", price: 699, category: "smartphones", brand: "Google" },
    { name: "Nvidia Shield TV Pro", description: "Streaming media player with 4K HDR", price: 199, category: "electronics", brand: "Nvidia" },
    { name: "Apple Mac Mini M1", description: "Compact desktop with M1 chip for great performance", price: 699, category: "electronics", brand: "Apple" },
    { name: "Bose SoundSport Free", description: "True wireless sport headphones", price: 199, category: "headphones", brand: "Bose" },
    { name: "Sony SRS-XB43", description: "Wireless Bluetooth speaker with deep bass", price: 249, category: "electronics", brand: "Sony" },
    { name: "Razer Huntsman Elite", description: "RGB mechanical gaming keyboard with fast switches", price: 199, category: "electronics", brand: "Razer" },
    { name: "Corsair K95 RGB Platinum", description: "Premium mechanical gaming keyboard", price: 199, category: "electronics", brand: "Corsair" },
    { name: "Xiaomi Mi 11", description: "Flagship Android phone with solid performance", price: 749, category: "smartphones", brand: "Xiaomi" },
    { name: "Huawei P40 Pro", description: "Smartphone with Leica quad camera system", price: 899, category: "smartphones", brand: "Huawei" },
    { name: "Acer Nitro 5", description: "Gaming laptop with Ryzen 5 and GTX 1650", price: 899, category: "laptops", brand: "Acer" },
    { name: "Lenovo Legion 5 Pro", description: "Gaming laptop with AMD Ryzen 7 and RTX 3060", price: 1400, category: "laptops", brand: "Lenovo" },
    { name: "Oculus Rift S", description: "Virtual reality headset for immersive gaming", price: 399, category: "gaming", brand: "Oculus" },
    { name: "Razer DeathAdder Elite", description: "Ergonomic gaming mouse with RGB lighting", price: 60, category: "electronics", brand: "Razer" },
    { name: "Samsung QN90A Neo QLED TV", description: "High-end 4K TV with excellent picture quality", price: 1999, category: "electronics", brand: "Samsung" },
    { name: "Canon EOS 90D", description: "DSLR camera with high resolution and fast autofocus", price: 1299, category: "cameras", brand: "Canon" }
  ];
  